# Site settings
title: Torricelli Blog
SEOTitle: Torricelli Blog
header-img: img/home-bg.jpg
email: 3218732070@qq.com
description: "这里是 @Torricelli 的个人博客，记录学习与成长"
keyword: "Torricelli"
url: "https://Torricelli.github.io"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: Torricelli
youtube_channel: UCVpuQ-wd6TkpX_uScDCgrUA

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true

plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sidebar settings
sidebar: true
sidebar-about-description: "做一个生活上 earnest 的人 <br> email: 3218732070@qq.com"
sidebar-avatar: /img/myBlog.png

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page
page-mathjax: false

# Friends
friends: []
